apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: "clockaks01-528d"
    labels:
        app: "clockaks01-528d"
    annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
    rules:
        - host: django-aks-ingress.australiaeast.cloudapp.azure.com
          http:
            paths:
            - path: /
              pathType: Prefix
              backend:
                service:
                  name: "clockaks01-528d"
                  port: 
                    number: 8000
