# Generated by Django 4.0.3 on 2022-03-30 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreturn', '0002_taxreturn_full_name_taxreturn_sin'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreturn',
            name='year',
            field=models.CharField(choices=[('2021', '2021'), ('2020', '2020'), ('2019', '2019')], default='2021', max_length=4),
        ),
    ]
