# Generated by Django 4.0.3 on 2022-03-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreturn', '0004_alter_taxreturn_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreturn',
            name='sin',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
