# Generated by Django 4.0.3 on 2022-04-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreturn', '0005_alter_taxreturn_sin_alter_taxreturn_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreturn',
            name='paymentcompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
