# Generated by Django 4.0.3 on 2022-04-12 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxreturn', '0006_taxreturn_paymentcompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreturn',
            name='memo',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
