on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: clockacr01.azurecr.io
        username: ${{ secrets.acr_clockacr01_username }}
        password: ${{ secrets.acr_clockacr01_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/docker-azure" -f  "docker-azure/dockerfile" -t clockacr01.azurecr.io/clockaks01:${{ github.sha }} --label dockerfile-path=docker-azure/dockerfile
        docker push clockacr01.azurecr.io/clockaks01:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clockaks01_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clockaks019069 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clockaks019069`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clockaks019069
        container-registry-url: clockacr01.azurecr.io
        container-registry-username: ${{ secrets.acr_clockacr01_username }}
        container-registry-password: ${{ secrets.acr_clockacr01_password }}
        secret-name: clockaks01dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clockaks019069
        manifests: |
          manifests/deployment-1.yml
          manifests/service-1.yml
          manifests/ingress-1.yml
        images: |
          clockacr01.azurecr.io/clockaks01:${{ github.sha }}
        imagepullsecrets: |
          clockaks01dockerauth
